services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: weather-forecaster-agent
    container_name: weather-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: weather-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge
