# fly.toml app configuration file generated for weather-forecaster-agent on 2025-09-01T13:50:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weather-forecaster-agent'
primary_region = 'sea'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = 'php /var/www/html/artisan migrate --force'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_URL = 'https://weather-forecaster-agent.fly.dev'
  DB_CONNECTION = 'sqlite'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'

[[mounts]]
  source = 'weather_agent_data'
  destination = '/var/www/html/storage'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
