app = "weather-forecaster-agent"
primary_region = "sea"  # Seattle - change to a region closest to you
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  DB_CONNECTION = "sqlite"
  APP_URL = "https://weather-forecaster-agent.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "weather_agent_data"
  destination = "/var/www/html/storage"
